version: '3' 
services:
  web:
    build: .
    ports:
      - 8000:8000
    environment:
      DEBUG: 'true'
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    command: /usr/local/bin/gunicorn underrated.wsgi -w 2 -b :8000
    restart: always
  nginx:
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - /www/static
      - .:/usr/src/app
    links:
      - web:web
    restart: always
  mongodb:
    image: mongo:latest
    volumes:
      - ./data/db:/data/db
      - ./mongo:/etc
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null --config /etc/mongod.conf

